version: "3.9"  # optional since v1.27.0
services:
  api:
    depends_on:
      - mongodb
    build: ./api
    ports:
      - "4000:8080"
    volumes:
      - api_node_modules:/usr/src/app/node_modules/ # This will preserve the node_modules that is installed in the docker container
      - ./api:/usr/src/app
  web:
    build: ./app
    ports:
      - "8080:8080"
    volumes:
      - app_node_modules:/usr/src/app/node_modules/ # This will preserve the node_modules that is installed in the docker container
      - ./app:/usr/src/app

  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  
volumes:
  api_node_modules:
  app_node_modules:
  mongodb_data_container: